// ── Dark theme: Catppuccin Mocha ──────────────────────────────
export const darkTheme = {
  'code[class*="language-"]': {
    color: '#cdd6f4', background: 'none',
    fontFamily: "'JetBrains Mono','Fira Code',monospace",
    fontSize: '0.855rem', textAlign: 'left',
    whiteSpace: 'pre', wordSpacing: 'normal', wordBreak: 'normal',
    lineHeight: '1.8', tabSize: 2, hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#cdd6f4', background: '#0d0f1a',
    padding: '1.5rem', margin: 0, overflow: 'auto', borderRadius: 0,
  },
  'comment':            { color: '#585b70', fontStyle: 'italic' },
  'block-comment':      { color: '#585b70', fontStyle: 'italic' },
  'prolog':             { color: '#585b70' },
  'doctype':            { color: '#585b70' },
  'cdata':              { color: '#585b70' },
  'punctuation':        { color: '#9399b2' },
  'namespace':          { opacity: 0.7 },
  'keyword':            { color: '#cba6f7' },
  'tag':                { color: '#cba6f7' },
  'selector':           { color: '#cba6f7' },
  'important':          { color: '#cba6f7', fontWeight: 'bold' },
  'atrule':             { color: '#cba6f7' },
  'operator':           { color: '#89dceb' },
  'symbol':             { color: '#89dceb' },
  'interpolation':      { color: '#89dceb' },
  'interpolation-punctuation': { color: '#89dceb' },
  'template-punctuation': { color: '#cba6f7' },
  'builtin':            { color: '#f9e2af' },
  'entity':             { color: '#f9e2af' },
  'url':                { color: '#f9e2af' },
  'decorator':          { color: '#f9e2af' },
  'annotation':         { color: '#f9e2af' },
  'string':             { color: '#a6e3a1' },
  'char':               { color: '#a6e3a1' },
  'attr-value':         { color: '#a6e3a1' },
  'template-literal':   { color: '#a6e3a1' },
  'regex':              { color: '#f38ba8' },
  'class-name':         { color: '#f38ba8' },
  'generic':            { color: '#f38ba8' },
  'number':             { color: '#fab387' },
  'boolean':            { color: '#fab387' },
  'constant':           { color: '#fab387' },
  'unit':               { color: '#fab387' },
  'function':           { color: '#89b4fa' },
  'function-name':      { color: '#89b4fa' },
  'property':           { color: '#89b4fa' },
  'attr-name':          { color: '#89b4fa' },
  'command':            { color: '#89b4fa' },
  'variable':           { color: '#cdd6f4' },
  'parameter':          { color: '#cdd6f4' },
  'pseudo-class':       { color: '#94e2d5' },
  'pseudo-element':     { color: '#94e2d5' },
  'flag':               { color: '#94e2d5' },
  'key':                { color: '#f38ba8' },
  'value':              { color: '#a6e3a1' },
  'deleted':            { color: '#f38ba8', background: 'rgba(243,139,168,0.12)' },
  'inserted':           { color: '#a6e3a1', background: 'rgba(166,227,161,0.12)' },
  'bold':               { fontWeight: 'bold' },
  'italic':             { fontStyle: 'italic' },
  'title':              { color: '#89b4fa', fontWeight: 'bold' },
  'hex-color':          { color: '#a6e3a1' },
}

// ── Light theme: Catppuccin Latte ─────────────────────────────
export const lightTheme = {
  'code[class*="language-"]': {
    color: '#4c4f69', background: 'none',
    fontFamily: "'JetBrains Mono','Fira Code',monospace",
    fontSize: '0.855rem', textAlign: 'left',
    whiteSpace: 'pre', wordSpacing: 'normal', wordBreak: 'normal',
    lineHeight: '1.8', tabSize: 2, hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#4c4f69', background: '#f5f5f5',
    padding: '1.5rem', margin: 0, overflow: 'auto', borderRadius: 0,
  },
  'comment':            { color: '#acb0be', fontStyle: 'italic' },
  'block-comment':      { color: '#acb0be', fontStyle: 'italic' },
  'prolog':             { color: '#acb0be' },
  'doctype':            { color: '#acb0be' },
  'cdata':              { color: '#acb0be' },
  'punctuation':        { color: '#8c8fa1' },
  'namespace':          { opacity: 0.7 },
  'keyword':            { color: '#8839ef' },   // mauve
  'tag':                { color: '#8839ef' },
  'selector':           { color: '#8839ef' },
  'important':          { color: '#8839ef', fontWeight: 'bold' },
  'atrule':             { color: '#8839ef' },
  'operator':           { color: '#04a5e5' },   // sky
  'symbol':             { color: '#04a5e5' },
  'interpolation':      { color: '#04a5e5' },
  'interpolation-punctuation': { color: '#8839ef' },
  'template-punctuation': { color: '#8839ef' },
  'builtin':            { color: '#df8e1d' },   // yellow
  'entity':             { color: '#df8e1d' },
  'url':                { color: '#df8e1d' },
  'decorator':          { color: '#df8e1d' },
  'annotation':         { color: '#df8e1d' },
  'string':             { color: '#40a02b' },   // green
  'char':               { color: '#40a02b' },
  'attr-value':         { color: '#40a02b' },
  'template-literal':   { color: '#40a02b' },
  'regex':              { color: '#d20f39' },   // red
  'class-name':         { color: '#d20f39' },
  'generic':            { color: '#d20f39' },
  'number':             { color: '#fe640b' },   // peach
  'boolean':            { color: '#fe640b' },
  'constant':           { color: '#fe640b' },
  'unit':               { color: '#fe640b' },
  'function':           { color: '#1e66f5' },   // blue
  'function-name':      { color: '#1e66f5' },
  'property':           { color: '#1e66f5' },
  'attr-name':          { color: '#1e66f5' },
  'command':            { color: '#1e66f5' },
  'variable':           { color: '#4c4f69' },
  'parameter':          { color: '#4c4f69' },
  'pseudo-class':       { color: '#179299' },   // teal
  'pseudo-element':     { color: '#179299' },
  'flag':               { color: '#179299' },
  'key':                { color: '#d20f39' },
  'value':              { color: '#40a02b' },
  'deleted':            { color: '#d20f39', background: 'rgba(210,15,57,0.08)' },
  'inserted':           { color: '#40a02b', background: 'rgba(64,160,43,0.08)' },
  'bold':               { fontWeight: 'bold' },
  'italic':             { fontStyle: 'italic' },
  'title':              { color: '#1e66f5', fontWeight: 'bold' },
  'hex-color':          { color: '#40a02b' },
}
